<a href="https://colab.research.google.com/github/jyotish123-hub/Data-Visualization/blob/main/25Aug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.arange(10)
a.shape
# a.ndim
a.dtype
a.itemsize
a=a.astype("float32") #32 is in bit
a.itemsize #in type

4

In [7]:
arr=np.arange(20)
arr=arr.reshape(4,5)
arr[0][1:4]

array([1, 2, 3])

In [8]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
print(arr)
arr[1:3,2:4]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 7,  8],
       [12, 13]])

In [17]:
print(arr)
arr[0:4,1:4]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [18]:
li=[1,5,6,8,9,10,12]
print(type(li))
arr2=np.array(li) #2nd method to create np array
arr2

<class 'list'>


array([ 1,  5,  6,  8,  9, 10, 12])

In [19]:
li=[[3,4],[4,5],[6,70]]
print(type(li))
arr2=np.array(li)
arr2


<class 'list'>


array([[ 3,  4],
       [ 4,  5],
       [ 6, 70]])

In [20]:
np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])